{"tag": "function", "depth": 2, "time": 1626947317.483104, "data": {"name": "try_log_screen", "call_args": {"screen": null, "quality": null, "max_size": null}, "start_time": 1626947317.1497521, "ret": {"screen": "1626947317468.jpg", "resolution": [720, 1280]}, "end_time": 1626947317.483086}}
{"tag": "info", "depth": 1, "time": 1626947317.485038, "data": {"name": "Final Error", "traceback": "Traceback (most recent call last):\n  File \"/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/poco/proxy.py\", line 26, in wrapped\n    proxy.wait_for_appearance(timeout=proxy.poco._pre_action_wait_for_appearance)\n  File \"/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/poco/proxy.py\", line 681, in wait_for_appearance\n    raise PocoTargetTimeout('appearance', self)\npoco.exceptions.PocoTargetTimeout: Waiting timeout for appearance of \"UIObjectProxy of \"\u9996\u9875\"\"\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/airtest/cli/runner.py\", line 70, in runTest\n    exec(compile(code.encode(\"utf-8\"), pyfilepath, 'exec'), self.scope)\n  File \"/Users/guokairong/Downloads/media-airtest/News_In_Picture_Vote-14.air/News_In_Picture_Vote-14.py\", line 12, in <module>\n    poco(\"\u9996\u9875\").click()\n  File \"/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/poco/proxy.py\", line 29, in wrapped\n    raise e\n  File \"/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/poco/proxy.py\", line 23, in wrapped\n    return func(proxy, *args, **kwargs)\n  File \"/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/poco/proxy.py\", line 332, in click\n    pos_in_percentage = self.get_position(focus)\n  File \"/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/poco/proxy.py\", line 72, in wrapped\n    return func(proxy, *args, **kwargs)\n  File \"/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/poco/proxy.py\", line 613, in get_position\n    pos = self.attr('pos')\n  File \"/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/poco/proxy.py\", line 39, in wrapped\n    return func(self, *args, **kwargs)\n  File \"/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/poco/proxy.py\", line 734, in attr\n    nodes = self._do_query(multiple=False)\n  File \"/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/poco/proxy.py\", line 874, in _do_query\n    raise PocoNoSuchNodeException(self)\npoco.exceptions.PocoNoSuchNodeException: Cannot find any visible node by query UIObjectProxy of \"\u9996\u9875\"\n"}}
{"tag": "function", "depth": 1, "time": 1626947320.5100212, "data": {"name": "sleep", "call_args": {"secs": 3}, "start_time": 1626947317.508082, "ret": null, "end_time": 1626947320.509943}}
